package com.manishjavadev.service.accounts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-03-02T00:43:54.626+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.manishjavadev.com/service/Accounts/", name = "Accounts")
@XmlSeeAlso({com.manishjavadev.schema.account.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Accounts {

    @WebMethod(operationName = "ProcessAccountInqury", action = "http://www.manishjavadev.com/service/Accounts/ProcessAccountInqury")
    @WebResult(name = "accountInquiryResponse", targetNamespace = "http://www.manishjavadev.com/schema/Account", partName = "accountInquiryResponse")
    public com.manishjavadev.schema.account.AccountInquiryResponseType processAccountInqury(
        @WebParam(partName = "accountInquiryRequest", name = "accountInquiryRequest", targetNamespace = "http://www.manishjavadev.com/schema/Account")
        com.manishjavadev.schema.account.AccountInquiryRequestType accountInquiryRequest
    );
}
